"""
Goal rendering, checked against goals Lean actually emitted.

WHY THIS FILE EXISTS
--------------------
`_parse_goal_string` rebuilt Lean's goal text into hypothesis/target fields,
and both the prompt shown to the model and the state-identity hash were built
from the rebuilt version. Lean wraps long lines; the parser understood only
one-line entries. So a hypothesis whose type wrapped lost its name line and
its continuation lines and vanished entirely, a wrapped target was cut off
after its first line, and a continuation line containing a colon was rendered
as an invented hypothesis. Measured over 3704 recorded goals: 890 corrupted
(24%). Of 1061 deleted hypotheses, most were the model's own `have`
sub-lemmas — 218 named `key` — because a decomposition is exactly the kind of
long statement that wraps. The model noticed and misdiagnosed it 53 times
across 20 traces ("the goal displays only '⊢ ∀ (n : ℕ),' which is
truncated/abnormal").

It survived for months with a green suite because every test was hand-written,
and hand-written mocks encode what we BELIEVE Lean returns. The tests fed the
parser tidy single-line goals it could handle.

So these tests are not hand-written. Their inputs are sampled from real
recorded REPL responses (tests/fixtures/lean_goals.jsonl, regenerated by
scripts/build_goal_fixture.py), weighted toward the shapes that broke it.
58 of the 67 fixture goals would fail on the old implementation.
"""

import json
from pathlib import Path

import pytest

from lean.repl import _parse_goals
from core.proof_state import ProofState

FIXTURE = Path(__file__).parent.parent / "fixtures" / "lean_goals.jsonl"


def _recorded():
    with open(FIXTURE, encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


RECORDED = _recorded()


def _legacy_render(goal_str: str) -> str:
    """The removed implementation, kept ONLY so the fixture can prove it has
    teeth (see test_fixture_would_catch_the_regression). Never call it for
    anything else — this is the bug, preserved as a specimen."""
    hyps, target = [], None
    for line in goal_str.strip().split("\n"):
        line = line.strip()
        if line.startswith("⊢"):
            target = line[1:].strip()
        elif " : " in line:
            name, type_ = line.split(" : ", 1)
            hyps.append((name.strip(), type_.strip()))
    if target is None:
        target = goal_str.strip()
    body = "\n".join(f"{n} : {t}" for n, t in hyps)
    return f"{body}\n⊢ {target}" if body else f"⊢ {target}"


class TestRecordedGoalsSurviveVerbatim:

    @pytest.mark.parametrize(
        "row", RECORDED, ids=[f"{r['run'][-6:]}#{r['seq']}" for r in RECORDED]
    )
    def test_goal_reaches_the_model_byte_identically(self, row):
        """The invariant that replaced the parser: what Lean said is what the
        model is shown. Nothing added, nothing dropped, nothing reordered."""
        assert _parse_goals([row["goal"]])[0].serialize() == row["goal"]

    def test_every_difficult_shape_is_covered(self):
        """Guards the fixture itself: if a regeneration stops sampling the
        shapes that broke the old parser, these tests quietly stop testing."""
        covered = {s for row in RECORDED for s in row["shapes"]}
        assert {
            "wrapped_hypothesis",       # was silently deleted
            "wrapped_target",           # was truncated after line 1
            "continuation_with_colon",  # became an invented hypothesis
            "case_label",
            "inaccessible_name",
            "plain",
        } <= covered

    def test_fixture_would_catch_the_regression(self):
        """The fixture is only worth having if it fails on the old code."""
        broken = [r for r in RECORDED if _legacy_render(r["goal"]) != r["goal"]]
        assert len(broken) > 40, (
            f"only {len(broken)}/{len(RECORDED)} fixture goals expose the bug — "
            "the sample has lost its teeth, regenerate it"
        )


class TestRecordedGoalsKeepTheirIdentity:
    """stable_hash decides whether two branches are the same proof position.
    Computed from the parsed fields it merged states differing only in a
    deleted hypothesis — 17 buckets of genuinely different goals collided,
    so the search could reuse the wrong Lean state or discard a real one."""

    def test_distinct_recorded_goals_get_distinct_hashes(self):
        by_hash = {}
        for row in RECORDED:
            h = ProofState(goals=_parse_goals([row["goal"]])).stable_hash()
            by_hash.setdefault(h, []).append(row["goal"])
        collisions = {h: v for h, v in by_hash.items() if len(v) > 1}
        assert not collisions, (
            f"{sum(len(v) - 1 for v in collisions.values())} distinct recorded "
            f"goals share a hash"
        )

    def test_the_legacy_rendering_did_collide_on_this_fixture(self):
        """Shows the collision was real, not theoretical, on recorded data."""
        seen = {}
        for row in RECORDED:
            seen.setdefault(_legacy_render(row["goal"]), []).append(row["goal"])
        assert any(len(v) > 1 for v in seen.values())
